name: Tracio
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.6
  get_it:
  dartz:
  path_provider:
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_messaging: ^15.2.5
  jwt_decoder:
  path: ^1.9.0

  cloud_firestore:
  cupertino_icons: ^1.0.8
  animated_bottom_navigation_bar: ^1.3.3
  flutter_screenutil: ^5.9.3
  google_nav_bar: ^5.0.7
  sliding_up_panel: ^2.0.0+1
  slide_to_act: ^2.0.2
  fl_chart: ^0.71.0
  grpc: ^4.0.1
  protobuf: ^3.1.0
  signalr_netcore: ^1.4.3

  uuid: ^4.2.1
  # Maps
  mapbox_maps_flutter: ^2.6.0
  geolocator: ^13.0.3
  location: ^8.0.0
  google_polyline_algorithm: ^3.1.0
  map_elevation: ^2.0.0
  latlong2: ^0.8.0
  turf: ^0.0.10
  #Permission
  permission_handler: ^11.3.1
  # Notifications
  flutter_local_notifications: ^18.0.1
  # Background Service
  flutter_background_service: ^5.1.0
  #Image saver
  gal: ^2.3.1
  #Handle debounce throttling
  easy_debounce: ^2.0.3
  battery_plus: ^6.2.1

  flutter_dotenv: ^5.2.1
  hydrated_bloc:
  dio: ^5.8.0+1
  logger:
  shared_preferences:
  carousel_slider:
  image_picker: ^1.1.2
  photo_manager: ^3.6.4
  image: ^4.5.4
  photo_view: ^0.15.0

  internet_connection_checker:
  connectivity_plus:
  equatable:
  flutter_secure_storage: ^9.2.4
  flutter_easyloading:
  timeago:
  cached_network_image:
  flutter_sticky_header:
  fixnum: ^1.1.1
  intl:
  flutter_rating_bar:
  shimmer:
  badges:
  animated_toggle_switch:
  loading_animation_widget:
  google_sign_in: ^6.3.0
  device_info_plus:
  android_id:
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/laucher_icon.png"

dev_dependencies:
  protoc_plugin: ^21.1.2
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.4.0
  flutter_lints: ^5.0.0
  web_socket_channel: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    # - assets/fonts/
    - assets/images/
    - assets/vectors/

    # token
    - .env
